blueprint:
  name: Motion and brightness activated lights
  description: Turn on lights when motion is detected and it is dark enough.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    brightness_sensor:
      name: Brightness Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    lights:
      name: Lights to control
      selector:
        target:
          entity:
            domain: light
    max_brightness:
      name: Maximum brightness
      description: Brightness trigger level. If it gets any brighter the lights will not be turned on.
      default: 30
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

variables:
  lights: !input lights

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

condition:
  - condition: or
    conditions:
      # dark enough
      - condition: numeric_state
        entity_id: !input brightness_sensor
        below: !input max_brightness
      # sun has set
      - condition: sun
        before: sunrise
        after: sunset
      # light is already turned on
      - "{{ expand(lights.entity_id) | selectattr('state', '==', 'on') | list | count > 0 }}"

action:
  - service: light.turn_on
    target: !input lights
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_sensor
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input lights
